# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.send_pings", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage", "");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.18pre");
user_pref("browser.startup.page", 0);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("cookiesafe.updateUrl", "");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.storage.enabled", false);
user_pref("extensions.bprivacy.AutoDelLSOnExitMode", 0);
user_pref("extensions.bprivacy.AutoDelLSOnStart", false);
user_pref("extensions.bprivacy.DefaultFlashCookieDeletion", false);
user_pref("extensions.bprivacy.DelTimerInterval", 7200);
user_pref("extensions.bprivacy.NotifyDuration", 0);
user_pref("extensions.bprivacy.NotifyOnNewLSO", 0);
user_pref("extensions.bprivacy.alwaysReScan", false);
user_pref("extensions.bprivacy.delDirs", true);
user_pref("extensions.bprivacy.domclear", true);
user_pref("extensions.bprivacy.donotaskonexit", true);
user_pref("extensions.bprivacy.initiated", true);
user_pref("extensions.bprivacy.sendpings.allowed", false);
user_pref("extensions.bprivacy.keycode", 0);
user_pref("extensions.bprivacy.lastSession", "Tue 26 Apr 2011 07:02:23 PM MSK");
user_pref("extensions.bprivacy.removedSession", 0);
user_pref("extensions.bprivacy.timer", "");
user_pref("extensions.bprivacy.useDelTimer", false);
user_pref("extensions.bprivacy.useDelTimerDelay", true);
user_pref("extensions.enabledItems", "{3d7eb24f-2740-49df-8937-200b1cc08f8a}:1.5.14.2,{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}:1.50,{9D23D0AA-D8F5-11DA-B3FC-0928ABF316DD}:3.0.5,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.18pre");
user_pref("extensions.lastAppVersion", "3.6.18pre");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("flashblock.enabled", true);
user_pref("flashblock.silverlight.blocked", true);
user_pref("flashblock.whitelist", "");
user_pref("geo.enabled", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.sendRefererHeader", 0);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.rememberSignons", false);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
